export { isArray } from "./isArray.js"
export { isBoolean } from "./isBoolean.js";
export { isDate } from "./isDate.js"
export { isFunction } from "./isFunction.js";
export { isInstanceOf } from "./isInstanceOf.js";
export { isNull } from "./isNull.js";
export { isNumber } from "./isNumber.js";
export { isObject } from "./isObject.js";
export { isString } from "./isString.js";
export { isUndefined } from "./isUndefined.js";